;;; -*- Mode:Lisp; Syntax:ANSI-Common-Lisp; Coding:utf-8 -*-

(in-package #:cl-num-utils-tests)

(deftestsuite sub-tests (cl-num-utils-tests)
  ()
  (:equality-test #'equalp))

(addtest (sub-tests)
  test-sub
  (let ((a (ia 3 4)))
    (ensure-same (sub a (si 0 -1) (si 0 -1))
                 #2A((0 1 2)
                     (4 5 6)))
    (ensure-same (sub a (si 1 -1) t)
                 #2A((4 5 6 7)))
    (ensure-same (sub a 1 t)
                 #(4 5 6 7))
    (ensure-same (sub a (rev t) (cat (si 0 2) (si 2 4)))
                 #2A((8 9 10 11)
                     (4 5 6 7)
                     (0 1 2 3)))
    (ensure (not (equalp (sub a 1 t)
                         #2A((4 5 6 7)))))))

(addtest (sub-tests)
  test-setf-sub
  (let ((b (ia 2 3)))
    (let ((a (ia 3 4)))
      (ensure-same (setf (sub a (si 1 0) (si 1 0)) b) b)
      (ensure-same a #2A((0 1 2 3)
                         (4 0 1 2)
                         (8 3 4 5)))
      (ensure-same b (ia 2 3)))
    (let ((a (ia 3 4)))
      (ensure-same (setf (sub a (si 0 -1) #(3 2 1)) b) b)
      (ensure-same a #2A((0 2 1 0)
                         (4 5 4 3)
                         (8 9 10 11)))
      (ensure-same b (ia 2 3))
      (ensure-error (setf (sub a 2 4) (list 3)))
      (ensure-error (setf (sub a 2 4) (vector 3))))))

(addtest (sub-tests)
  map-columns
  (ensure-same (map-columns #'sum (ia 3 4))
               #(12 15 18 21))
  (ensure-same (map-columns (lambda (col) (vector (sum col) (mean col))) (ia 3 4))
               #2A((12 15 18 21)
                   (4 5 6 7))))

(addtest (sub-tests)
  map-rows
  (ensure-same (map-rows #'sum (ia 4 3))
               #(3 12 21 30))
  (ensure-same (map-rows (lambda (col) (vector (sum col) (mean col))) (ia 4 3))
               #2A((3 1)
                   (12 4)
                   (21 7)
                   (30 10))))

(addtest (sub-tests)
  reshape-calculate-dimensions
  (ensure-same (reshape-calculate-dimensions #(1 2 3) 6) #(1 2 3))
  (ensure-same (reshape-calculate-dimensions #(1 t 3) 6) #(1 2 3))
  (ensure-same (reshape-calculate-dimensions #(1 t 3) 0) #(1 0 3))
  (ensure-error (reshape-calculate-dimensions #(1 t t 3) 6))
  (ensure-error (reshape-calculate-dimensions #(1 t 0 3) 6)))

(addtest (sub-tests)
  reshape
  (let ((a (ia 3 4))
        (a-reshaped-rm #2A((0 1 2)
                           (3 4 5)
                           (6 7 8)
                           (9 10 11))))
    (ensure-same (reshape a '(4 t) :row-major) a-reshaped-rm)
    (ensure-same (reshape a '(4 t) :row-major :copy t) a-reshaped-rm)
    (ensure-same (reshape a '(4 t) :column-major) 
                 #2A((0 5 10)
                     (4 9 3)
                     (8 2 7)
                     (1 6 11)))))
